export const PATHS = {
  root: "/",
  contact: "/contact",
  about: "/about",
  login: "/login",
  signup: "/signup",
  main_products_page: "/main_products_page",
  singleproduct: "/singleproduct/:id",
  add_to_cart: "/add_to_cart",
  forgatepass: "/forgatepass",
  password_reset: "/resetpassword/:token",
  setting: "/setting",
  order: "/order",
  adminHome: "/adminHome",
  dashboard: "/",
  adminOrder: "/adminOrder",
  checkout: "/checkout",
};
